name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_NAME: MyApp
  NODEJS_VERSION: 24

jobs:
  test:
    name: Analyze bundle with React Native ${{ matrix.rn-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rn-version: [latest, 0.83.4, 0.82.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: 'yarn'

      - name: Install React Native ${{ matrix.rn-version }} and run the visualizer
        working-directory: /tmp
        shell: bash
        run: |
          set -x # print all executed commands
          npx @react-native-community/cli@latest init ${{ env.APP_NAME }} --version ${{ inputs.rn-ver }} --skip-git-init --install-pods false --pm yarn
          cd ${{ env.APP_NAME }}
          yarn add react-native-bundle-visualizer@portal:${{ github.workspace }}
          yarn run react-native-bundle-visualizer --verbose
