name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_NAME: MyApp
  NODEJS_VERSION: 24

jobs:
  pure_rn:
    if: false
    name: Analyze bundle with React Native ${{ matrix.rn-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rn-version: [latest, 0.83.4, 0.82.1] # Three latest major versions of React Native
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: 'yarn'

      - name: Install node_modules in ${{ github.workspace }}
        run: yarn install --frozen-lockfile

      - name: Install React Native ${{ matrix.rn-version }} and run the visualizer
        working-directory: /tmp
        shell: bash
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          set -x # print all executed commands
          npx @react-native-community/cli@latest init ${{ env.APP_NAME }} --version ${{ matrix.rn-version }} --skip-git-init --install-pods false --pm yarn
          cd ${{ env.APP_NAME }}
          yarn add react-native-bundle-visualizer@portal:${{ github.workspace }} # yarn v2+ syntax
          yarn run react-native-bundle-visualizer --verbose --error-on-fail

  expo:
    name: Analyze bundle with Expo default@sdk-${{ matrix.expo-sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        expo-sdk: [ 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: 'yarn'

      - name: Install node_modules in ${{ github.workspace }}
        run: yarn install --frozen-lockfile

      - name: Install Expo and run the visualizer
        working-directory: /tmp
        shell: bash
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          set -x # print all executed commands
          if [[ ${{ matrix.expo-sdk }} -ge 40 && ${{ matrix.expo-sdk }} -le 50 ]]; then
            npx create-expo-app ${{ env.APP_NAME }} -t expo-template-blank@sdk-${{ matrix.expo-sdk }}
          else
            yarn create expo-app ${{ env.APP_NAME }} --template default@sdk-${{ matrix.expo-sdk }}
          fi
          cd ${{ env.APP_NAME }}
          yarn add ${{ github.workspace }} # yarn v1 syntax
          yarn run react-native-bundle-visualizer --verbose --expo --error-on-fail --bundle-output=./dist/ios.bundle
